// The backward-compatibility gate for multi-level plans.
//
// `test/__snapshots__/before-levels/` was generated by running the library at f398af5 —
// the tip of feature/artur_courtyards-and-fixtures *before* levels landed — by exporting
// that commit's `src` and `fixtures` and recording findings, schedule, drag edits,
// canonical text and SVG for each one. Nothing in this repository can regenerate it, and
// that is the point: it is evidence of what the library used to do, not a record of what
// it does now.
//
// A document with no `levels` block must still produce all of it byte for byte. The
// normalisation onto one level with a well-known id has to be invisible from outside.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { analyze, draggableWalls, formatText, parse, renderSvg, schedule } from "../src/index.ts";

const FIXTURES = ["casa-t3", "apartment-t2", "casa-piscina", "quinta", "casa-patio", "broken", "cabin"];
const load = (n: string) => readFileSync(new URL(`../fixtures/${n}.json`, import.meta.url), "utf8");
const baseline = (n: string, ext: string) =>
  readFileSync(new URL(`./__snapshots__/before-levels/${n}.${ext}`, import.meta.url), "utf8");

describe("levels: a single-level document is byte-identical to what it was before levels", () => {
  for (const name of FIXTURES) {
    it(`${name}: findings, schedule, drags and canonical text`, () => {
      const text = load(name);
      const plan = parse(JSON.parse(text));
      const { model, findings } = analyze(plan);
      const drags = [...draggableWalls(text, model).entries()]
        .map(([id, d]) => ({ id, writes: d.writes, edits: d.edits(d.c + 0.25) }))
        .sort((a, b) => a.id.localeCompare(b.id));
      const actual = `${JSON.stringify({ findings, schedule: schedule(model), drags, formatted: formatText(text) }, null, 2)}\n`;
      assert.equal(actual, baseline(name, "json"));
    });

    it(`${name}: the drawing`, () => {
      const { model, findings } = analyze(parse(JSON.parse(load(name))));
      assert.equal(renderSvg(model, { findings }), baseline(name, "svg"));
    });
  }

  it("carries no `level` on any finding of a single-level document", () => {
    for (const name of FIXTURES) {
      const { findings } = analyze(parse(JSON.parse(load(name))));
      for (const f of findings) assert.equal("level" in f, false, `${name}: ${f.rule} gained a level`);
    }
  });

  it("carries none even when a single-level document declares a vertical element", () => {
    // the one rule that can fire without a second level: a stair that joins nothing. It
    // is also the one place a level id could leak into output that has never had one.
    const { findings } = analyze(
      parse({
        walls: { exterior: 0.3, partition: 0.12 },
        rooms: { hall: { kind: "hall", rect: [0, 0, 3, 4] } },
        openings: [{ type: "door", between: ["exterior", "hall"], on: { room: "hall", side: "north" }, width: 1, entrance: true }],
        vertical: [{ id: "escada", type: "stairs", at: [{ level: "ground", in: "hall", rect: [0.5, 0.5, 1, 2] }] }],
      }),
    );
    const f = findings.find((x) => x.rule === "stair.no_arrival")!;
    assert.ok(f, `expected stair.no_arrival in ${findings.map((x) => x.rule).join(", ")}`);
    assert.equal("level" in f, false);
    assert.match(f.message, /^Stairs goes nowhere;/, "and it does not name a level the author never wrote");
  });

  it("keeps the schedule free of the multi-level sections", () => {
    for (const name of FIXTURES) {
      const s = schedule(analyze(parse(JSON.parse(load(name)))).model);
      assert.equal("levels" in s, false, name);
      assert.equal("building" in s, false, name);
    }
  });

  it("normalises to exactly one ground level with a well-known id", () => {
    const plan = parse(JSON.parse(load("casa-t3")));
    assert.equal(plan.levelled, false);
    assert.deepEqual(plan.levels.map((l) => [l.id, l.ground]), [["ground", true]]);
    // and the ground level's collections are the plan's own, not copies
    assert.equal(plan.rooms, plan.levels[0]!.rooms);
    assert.equal(plan.openings, plan.levels[0]!.openings);
  });
});
