// The example plans are the repository's own fixtures, imported as text rather than
// copied, so the playground and the library's tests always show the same documents.
//
// Cabana is loaded from its `.dsl` twin rather than its `.json` one: the two are the same
// building (fixtures/*.dsl are generated by `toDsl` and a test pins them to it), and the
// gallery is the natural place to meet the line syntax. The JSON | DSL toggle in the
// playground converts any of the others.
import apartmentT2 from "../../../fixtures/apartment-t2.json?raw";
import broken from "../../../fixtures/broken.json?raw";
import brokenLevels from "../../../fixtures/broken-levels.json?raw";
import cabin from "../../../fixtures/cabin.dsl?raw";
import casaPatio from "../../../fixtures/casa-patio.json?raw";
import casaPiscina from "../../../fixtures/casa-piscina.json?raw";
import casaT3 from "../../../fixtures/casa-t3.json?raw";
import moradia2Pisos from "../../../fixtures/moradia-2-pisos.json?raw";
import quinta from "../../../fixtures/quinta.json?raw";

export interface Example {
  id: string;
  name: string;
  /** one line on what this plan is here to show */
  shows: string;
  source: string;
}

export const EXAMPLES: Example[] = [
  { id: "casa-piscina", name: "Casa com Piscina", shows: "fixtures: an indoor pool, sanitary ware, a kitchen run", source: casaPiscina },
  { id: "casa-t3", name: "Casa T3", shows: "the seed house: thirteen rooms, eleven rects and two L-shapes", source: casaT3 },
  { id: "casa-patio", name: "Casa com Pátio", shows: "a courtyard — the Sala is lit only through it", source: casaPatio },
  { id: "quinta", name: "Quinta", shows: "an inner garden, a pool on a terrace, a detached shack", source: quinta },
  { id: "moradia-2-pisos", name: "Moradia de 2 pisos", shows: "two storeys: a shared track grid, a double-height void and a stair", source: moradia2Pisos },
  { id: "apartment-t2", name: "Apartamento T2", shows: "authored as a track grid instead of polygons", source: apartmentT2 },
  { id: "cabin", name: "Cabana", shows: "written in the line DSL: fourteen lines for the same building", source: cabin },
  { id: "broken", name: "Broken on purpose", shows: "one of every error the linter can report", source: broken },
  { id: "broken-levels", name: "Broken on purpose: levels", shows: "one of every cross-level error the linter can report", source: brokenLevels },
];

export const byId = (id: string): Example | undefined => EXAMPLES.find((e) => e.id === id);
